version: "3.7"
services:
   aws-iot-buildroot-build:
    build:
      context: ./
      args:
         BUILDROOT_USER: aws
         BUILDROOT_DIR: buildroot
         BUILDROOT_VERSION: 2021.02.3
         EXTERNAL_TREES: aws
         UID: 1000
         GID: 1000
    environment:
      - APPLY_CONFIGS
      - CLEAN_AFTER_BUILD
      - ENV_FILES
      - EXIT_AFTER_BUILD
      - NO_BUILD
      - UPDATE_DCFC_PROGRAMS
      - VERBOSE
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./:/mnt
      - aws-iot-buildroot-buildccache:/home/ccache
    image: aws-iot-buildroot-build:latest
    container_name:  aws-iot-buildroot-build
volumes:
  aws-iot-buildroot-buildccache:
