version: "3.7"
services:
   buildroot-aws-iot-build:
    build:
      context: ./
      args:
         BUILDROOT_USER: br-user
         BUILDROOT_DIR: buildroot
         BUILDROOT_VERSION: 2021.08.1
         EXTERNAL_TREES: aws
         BUILDROOT_PATCH_DIR: "aws/patches/buildroot"
         UID: 1000
         GID: 1000
    environment:
      - APPLY_CONFIGS
      - BUILD_PACKAGE
      - CLEAN_AFTER_BUILD
      - ENV_FILES
      - EXIT_AFTER_BUILD
      - NO_BUILD
      - SINGLE_TARGET
      - VERBOSE
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./:/mnt
      - buildroot-aws-iot-build-ccache:/home/br-user/ccache
    image: buildroot-aws-iot-build:latest
    container_name:  buildroot-aws-iot-build
volumes:
  buildroot-aws-iot-build-ccache:
