################################################################################
#
# amazon-kinesis-video-streams-producer-sdk-cpp
#
################################################################################

AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_VERSION = 3.3.0
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_SITE = $(call github,awslabs,amazon-kinesis-video-streams-producer-sdk-cpp,v$(AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_VERSION))
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_LICENSE = Apache-2.0
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_LICENSE_FILES = LICENSE
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_CPE_ID_VENDOR = amazon
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_INSTALL_STAGING = YES

AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_DEPENDENCIES = \
	amazon-kinesis-video-streams-producer-c \
	libcurl \
	openssl \
	log4cplus

# We manage our own dependencies
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_CONF_OPTS = \
	-DCMAKE_PREFIX_PATH="$(STAGING_DIR)/usr" \
	-DBUILD_DEPENDENCIES=OFF \
	-DBUILD_OPENSSL_PLATFORM=OFF \
	-DCODE_COVERAGE=OFF

ifeq ($(BR2_STATIC_LIBS),y)
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_CONF_OPTS += -DBUILD_STATIC=ON
else
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_CONF_OPTS += -DBUILD_STATIC=OFF
endif

ifeq ($(BR2_TOOLCHAIN_USES_MUSL),y)
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_CONF_OPTS += -DADD_MUCLIBC=ON
else ifeq ($(BR2_SHARED_LIBS),y)
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_CONF_OPTS += -DADD_MUCLIBC=OFF
endif

ifeq ($(AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_GSTREAMER_PLUGIN),y)
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_DEPENDENCIES += \
	gstreamer1 \
	gst1-plugins-base
AMAZON_KINESIS_VIDEO_STREAMS_PRODUCER_SDK_CPP_CONF_OPTS += \
	-DBUILD_GSTREAMER_PLUGIN=ON
endif

$(eval $(cmake-package))
