################################################################################
#
# amazon-kinesis-video-streams-webrtc-sdk-c
#
################################################################################

AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_VERSION = 1.5.0
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_SITE = $(call github,awslabs,amazon-kinesis-video-streams-webrtc-sdk-c,v$(AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_VERSION))
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_LICENSE = Apache-2.0
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_LICENSE_FILES = LICENSE
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_CPE_ID_VENDOR = amazon
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_INSTALL_STAGING = YES

AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_DEPENDENCIES = \
	amazon-kinesis-video-streams-pic \
	amazon-kinesis-video-streams-producer-c \
	jsmn \
	openssl \
	libsrtp \
	libwebsockets \
	usrsctp

# We manage our own dependencies
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_CONF_OPTS = \
	-DCMAKE_PREFIX_PATH="$(STAGING_DIR)/usr" \
	-DBUILD_DEPENDENCIES=OFF \
	-DBUILD_LIBSRTP_HOST_PLATFORM=linux \
	-DBUILD_LIBSRTP_DESTINATION_PLATFORM=linux \
	-DBUILD_SAMPLE=OFF \
	-DUSE_MBEDTLS=OFF \
	-DUSE_OPENSSL=ON \
	-DBUILD_OPENSSL_PLATFORM=linux

ifeq ($(BR2_STATIC_LIBS),y)
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_CONF_OPTS += -DBUILD_STATIC_LIBS=ON
else ifeq ($(BR2_SHARED_LIBS),y)
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_CONF_OPTS += -DBUILD_STATIC_LIBS=OFF
endif

ifeq ($(BR2_TOOLCHAIN_USES_MUSL),y)
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_CONF_OPTS += -DADD_MUCLIBC=ON
else ifeq ($(BR2_SHARED_LIBS),y)
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_CONF_OPTS += -DADD_MUCLIBC=OFF
endif

ifeq ($(BR2_PACKAGE_GSTREAMER1),y)
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_DEPENDENCIES += \
	gstreamer1 \
	gst1-plugins-base
endif

ifeq ($(BR2_PACKAGE_OPENSSL),y)
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_DEPENDENCIES += openssl
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_CONF_OPTS += \
	-DUSE_OPENSSL=ON \
	-DBUILD_OPENSSL_PLATFORM=linux
else
AMAZON_KINESIS_VIDEO_STREAMS_WEBRTC_SDK_C_CONF_OPTS += \
	-DUSE_OPENSSL=OFF
endif

$(eval $(cmake-package))
